baseURL = 'https://ctcanada.github.io/'
languageCode = 'en-us'
title = 'CTC'
theme = 'hugo-profile'

[params]
title = "Cyril Tax Canada"
staticPath = ""
favicon = "CTC.png"

animate = true

customScripts = """
<!-- Calendly badge widget begin -->
<link href="https://assets.calendly.com/assets/external/widget.css" rel="stylesheet">
<script src="https://assets.calendly.com/assets/external/widget.js" type="text/javascript" async></script>
<script type="text/javascript">window.onload = function() { Calendly.initBadgeWidget({ url: 'https://calendly.com/ctcanada/consultation?background_color=202020&text_color=ffffff&primary_color=ffbd3e', text: 'Book an appointment', color: '#ffbd3e', textColor: '#202020', branding: false }); }</script>
<!-- Calendly badge widget end -->
"""

[params.theme]
disableThemeToggle = true
defaultTheme = "dark"

[params.color]
#textColor = "#FFFFFF"
#secondaryTextColor = "#FFFFFF"
#backgroundColor = "#FFFFFF"
#secondaryBackgroundColor = "#FFFFFF"
#primaryColor = "#FFFFFF"
#secondaryColor = "#FFFFFF"

[params.color.darkmode]
#textColor = "#FFFFFF"
#secondaryTextColor = "#FFFFFF"
#backgroundColor = "#FFFFFF"
#secondaryBackgroundColor = "#FFFFFF"
#primaryColor = "#FFFFFF"
#secondaryColor = "#FFFFFF"

[params.navbar]
align = "ms-auto"
brandLogo = "CTC.png"
showBrandLogo = true
brandName = "CTC"

[params.hero]
enable = true
intro = "Welcome to"
title = "Cyril Tax Canada"
subtitle = "Tax Deadline"

customScripts = """
<script src="https://cdn.logwork.com/widget/countdown.js"></script>
<a href="https://logwork.com/countdown-8fpr" class="countdown-timer" data-style="circles" data-timezone="America/Toronto" data-background="#a81414" data-textcolor="#ffffff" data-date="2023-11-15 23:14" data-digitscolor="#ffbd3e" data-unitscolor="#ffffff">‎</a>
"""

[params.hero.socialLinks]
[[params.hero.socialLinks.customIcons]]
icon = "instagram.png"
url = "https://instagram.com/cyriltaxcanada?igshid=cWl1Ymtjb3RkcXR6&utm_source=qr"

[params.about]
enable = true
title = "Pricing"

[params.about.skills]
enable = true
title = "We offer personal tax filing for everyone, see our pricing guidelines below"
items = [
    "First Tax Filing",
    "Students",
    "Seniors (65+)",
    "Other Personal Filing"
]

[params.contact]
enable = true
title = "Contact Us"
content = "Reach out by email, we are always available"
email = "info.ctcanada@gmail.com"
btnName = "info.ctcanada@gmail.com"

[params.contact.formspree]
enable = true

[params.footer]
[params.footer.recentPosts]
enable = true
path = "blogs"
count = 3
title = "Recent Posts"
[params.footer.socialNetwork]
linkedin = "https://linkedin.com"
twitter = "https://twitter.com"
instagram = "https://instagram.com"
facebook = "https://facebook.com"

[params.terms]
read = "Read"
toc = "Table Of Contents"
copyright = "All Rights Reserved"
