baseURL = 'https://ctcanada.github.io/'
languageCode = 'en-us'
title = 'CTC'
theme = 'hugo-profile'

[Menus]
[[Menus.main]]
identifier = "faq"
name = "FAQ"
title = "FAQ"
url = "/blogs"

[[Menus.main]]

[params]
title = "Cyril Tax Canada"
staticPath = ""
favicon = "CTC.png"

animate = true

customScripts = """
<!-- Calendly badge widget begin -->
<link href="https://assets.calendly.com/assets/external/widget.css" rel="stylesheet">
<script src="https://assets.calendly.com/assets/external/widget.js" type="text/javascript" async></script>
<script type="text/javascript">window.onload = function() { Calendly.initBadgeWidget({ url: 'https://calendly.com/ctcanada/consultation?background_color=202020&text_color=ffffff&primary_color=ffbd3e', text: 'Book an appointment', color: '#ffbd3e', textColor: '#202020', branding: false }); }</script>
<!-- Calendly badge widget end -->
"""

[params.theme]
disableThemeToggle = true
defaultTheme = "dark"

[params.color]
#textColor = "#FFFFFF"
#secondaryTextColor = "#FFFFFF"
#backgroundColor = "#FFFFFF"
#secondaryBackgroundColor = "#FFFFFF"
#primaryColor = "#FFFFFF"
#secondaryColor = "#FFFFFF"

[params.color.darkmode]
#textColor = "#FFFFFF"
#secondaryTextColor = "#FFFFFF"
#backgroundColor = "#FFFFFF"
#secondaryBackgroundColor = "#FFFFFF"
#primaryColor = "#FFFFFF"
#secondaryColor = "#FFFFFF"

[params.navbar]
align = "ms-auto"
brandLogo = "CTC.png"
showBrandLogo = true
brandName = "CTC"

[params.hero]
enable = true
title = "Cyril Tax Canada"
subtitle = "Maximize returns and minimize stress"

customScripts = """
<p>&nbsp;</p><script src="https://cdn.logwork.com/widget/countdown.js"></script>
<a href="https://logwork.com/countdown-timer" class="countdown-timer" data-style="circles" data-timezone="America/Toronto" data-textcolor="#ffffff" data-date="2025-05-01 00:00" data-background="#ffbd3e" data-digitscolor="#ffffff" data-unitscolor="#ffffff">2025 Tax Deadline</a>
"""

[params.hero.bottomImage]
enable = false

[params.hero.socialLinks]
[[params.hero.socialLinks.customIcons]]



[params.achievements]
enable = true
title = "Services"

[[params.achievements.items]]
title = "First Tax Filing"
content = "Filing your first taxes? Do not worry! We will help you do it seamlessly."

[[params.achievements.items]]
title = "Students' Tax filing"
content = "For students currently attending college or university. Special discounts for Medical students in Canada and abroad!"

[[params.achievements.items]]
title = "Seniors' Tax filing"
content = "Anyone aged 65+"

[[params.achievements.items]]
title = "Tax Planning"
content = "To maximize your returns, we will help you plan ahead to navigate the different contribution programs."

[[params.achievements.items]]
title = "Debt planning"
content = "Having debts can be very stressful, we will help you make the right decisions to navigate debt consolidation."

[[params.achievements.items]]
title = "Bookkeeping Services"
content = "Bookkeeping services for your business or practice."

[[params.achievements.items]]
title = "Corporate Tax Preparation"
content = "All types of corporate tax preparation, processing and filing throughout the year for your business or practice."

[[params.achievements.items]]
title = "HST Returns"
content = "We will help you file HST on time."

[[params.achievements.items]]
title = "Payroll Processing"
content = "Time is of essence! We will help with payroll processing so you can focus on growing your business."

[[params.achievements.items]]
title = "Other Services"
content = "If you are looking for a service that is not on the website. Do not hesitate to get in touch to find out if we can help!"

[params.contact]
enable = true
title = "Contact Us"
content = """Reach out by email at info.ctcanada@gmail.com or by filling the form below, we are always available!"""
email = "info.ctcanada@gmail.com"
btnName = "Submit"

icon = "instagram.png"
url = "https://instagram.com/cyriltaxcanada"

[params.contact.formspree]
enable = true
formId = "xyyrekql"

[params.footer]
[params.footer.recentPosts]
enable = false
path = "blogs"
count = 3
title = "Recent Posts"
[params.footer.socialNetwork]
instagram = "https://instagram.com/cyriltaxcanada?igshid=cWl1Ymtjb3RkcXR6&utm_source=qr"

[params.terms]
read = "Read"
toc = "Table Of Contents"
copyright = "All Rights Reserved"
