baseURL = 'https://ctcanada.github.io/'
languageCode = 'en-us'
title = 'CTC'
theme = 'hugo-profile'

[Menus]
[[Menus.main]]
identifier = "faq"
name = "FAQ"
title = "FAQ"
url = "/blogs"

[[Menus.main]]

[params]
title = "Cyril Tax Canada"
staticPath = ""
favicon = "CTC.png"

animate = true

customScripts = """
<!-- Calendly badge widget begin -->
<link href="https://assets.calendly.com/assets/external/widget.css" rel="stylesheet">
<script src="https://assets.calendly.com/assets/external/widget.js" type="text/javascript" async></script>
<script type="text/javascript">window.onload = function() { Calendly.initBadgeWidget({ url: 'https://calendly.com/ctcanada/consultation?background_color=202020&text_color=ffffff&primary_color=ffbd3e', text: 'Book an appointment', color: '#ffbd3e', textColor: '#202020', branding: false }); }</script>
<!-- Calendly badge widget end -->
"""

[params.theme]
disableThemeToggle = true
defaultTheme = "dark"

[params.color]
#textColor = "#FFFFFF"
#secondaryTextColor = "#FFFFFF"
#backgroundColor = "#FFFFFF"
#secondaryBackgroundColor = "#FFFFFF"
#primaryColor = "#FFFFFF"
#secondaryColor = "#FFFFFF"

[params.color.darkmode]
#textColor = "#FFFFFF"
#secondaryTextColor = "#FFFFFF"
#backgroundColor = "#FFFFFF"
#secondaryBackgroundColor = "#FFFFFF"
#primaryColor = "#FFFFFF"
#secondaryColor = "#FFFFFF"

[params.navbar]
align = "ms-auto"
brandLogo = "CTC.png"
showBrandLogo = true
brandName = "CTC"

[params.hero]
enable = true
intro = "Welcome to"
title = "Cyril Tax Canada"
subtitle = "Tax Deadline"

customScripts = """
<script src="https://cdn.logwork.com/widget/countdown.js"></script>
<a href="https://logwork.com/countdown-4fji" class="countdown-timer" data-style="circles" data-timezone="America/Toronto" data-date="2024-04-30 11:33">Tax Deadline</a>
"""

[params.hero.bottomImage]
enable = false

[params.hero.socialLinks]
[[params.hero.socialLinks.customIcons]]

icon = "instagram.png"
url = "https://instagram.com/cyriltaxcanada?igshid=cWl1Ymtjb3RkcXR6&utm_source=qr"

[params.achievements]
enable = true
title = "Services & Pricing"

[[params.achievements.items]]
title = "First Tax Filing"
content = "For anyone filing tax for the first time within Canada (Starting $40)"

[[params.achievements.items]]
title = "Students"
content = "For students currently attending college or university (Starting $35)"

[[params.achievements.items]]
title = "Seniors"
content = "Anyone aged 65+ (Starting $35)"

[[params.achievements.items]]
title = "Other Personal Filing"
content = "Any other type of filing (Starting $60)"

[params.contact]
enable = true
title = "Contact Us"
content = """Reach out by email on info.ctcanada@gmail.com or by fill the form below, we are always available"""
email = "info.ctcanada@gmail.com"
btnName = "Submit"

[params.contact.formspree]
enable = true
formId = "xyyrekql"

[params.footer]
[params.footer.recentPosts]
enable = true
path = "blogs"
count = 3
title = "Recent Posts"
[params.footer.socialNetwork]
instagram = "https://instagram.com/cyriltaxcanada?igshid=cWl1Ymtjb3RkcXR6&utm_source=qr"

[params.terms]
read = "Read"
toc = "Table Of Contents"
copyright = "All Rights Reserved"
